import PDFDocument from 'pdfkit';

export function generateInvoicePdf(invoice: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const total = Number(invoice.amount) + Number(invoice.tax_amount || 0);
    const pageWidth = doc.page.width - 100;

    doc.fontSize(24).font('Helvetica-Bold').text('RECEIPT', 50, 50);

    doc.fontSize(10).font('Helvetica')
      .text(`#${invoice.invoice_number}`, 50, 78)
      .text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), { align: 'right' });

    doc.moveTo(50, 100).lineTo(doc.page.width - 50, 100).stroke('#e0e0e0');

    doc.fontSize(10).font('Helvetica-Bold').text('FROM', 50, 120);
    doc.font('Helvetica')
      .text(invoice.freelancer_name || '', 50, 138)
      .text(invoice.freelancer_business || '', 50, 154)
      .text(invoice.freelancer_contact || '', 50, 170);

    doc.fontSize(10).font('Helvetica-Bold').text('BILL TO', doc.page.width - 250, 120);
    doc.font('Helvetica')
      .text(invoice.client_name || '', doc.page.width - 250, 138)
      .text(invoice.client_company || '', doc.page.width - 250, 154)
      .text(invoice.client_email || '', doc.page.width - 250, 170);

    doc.moveTo(50, 195).lineTo(doc.page.width - 50, 195).stroke('#e0e0e0');

    const tableTop = 210;
    const col1 = 50;
    const col2 = doc.page.width - 200;
    const col3 = doc.page.width - 100;

    doc.fontSize(10).font('Helvetica-Bold')
      .text('Description', col1, tableTop)
      .text('Amount', col2, tableTop)
      .text('Total', col3, tableTop);

    doc.moveTo(50, tableTop + 18).lineTo(doc.page.width - 50, tableTop + 18).stroke('#e0e0e0');

    const rowY = tableTop + 28;
    doc.font('Helvetica')
      .text(invoice.service_desc || '', col1, rowY, { width: col2 - col1 - 20 })
      .text(`${invoice.currency || 'USD'} ${Number(invoice.amount).toFixed(2)}`, col2, rowY)
      .text(`${invoice.currency || 'USD'} ${Number(invoice.amount).toFixed(2)}`, col3, rowY);

    if (Number(invoice.tax_amount) > 0) {
      const taxY = rowY + 24;
      doc.fontSize(10).font('Helvetica')
        .text(invoice.tax_desc || 'Tax', col1, taxY)
        .text(`${invoice.currency || 'USD'} ${Number(invoice.tax_amount).toFixed(2)}`, col3, taxY);
    }

    const dividerY = (Number(invoice.tax_amount) > 0 ? rowY + 48 : rowY + 24) + 10;
    doc.moveTo(col2, dividerY).lineTo(doc.page.width - 50, dividerY).stroke('#e0e0e0');

    const totalY = dividerY + 10;
    doc.fontSize(12).font('Helvetica-Bold')
      .text('TOTAL', col1, totalY)
      .text(`${invoice.currency || 'USD'} ${total.toFixed(2)}`, col3, totalY);

    if (invoice.payment_terms) {
      const termsY = Math.max(totalY + 40, 400);
      doc.moveTo(50, termsY - 10).lineTo(doc.page.width - 50, termsY - 10).stroke('#e0e0e0');
      doc.fontSize(9).font('Helvetica-Bold').text('PAYMENT TERMS', 50, termsY + 4);
      doc.font('Helvetica').fontSize(9).text(invoice.payment_terms, 50, termsY + 20);
    }

    doc.fontSize(8).font('Helvetica').fillColor('#999')
      .text('Generated by The Hive', 50, doc.page.height - 50, { align: 'center' });

    doc.end();
  });
}
